dataset: CIFAR100
first_split_size: 10
other_split_size: 10
schedule:
- 80
- 0
- 20
schedule_type: coswm
batch_size: 128
optimizer: AdamW
lr: 0.005
momentum: 0.9
weight_decay: 0
iter_step: 40
model_type: zoo
model_name: vit_pt_imnet
max_task: -1
dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: True